config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # devise_for :users, controllers: { omniauth_callbacks: 'callbacks', registrations: 'registrations' }

  # ! use path below for testing basic setup
  # ! path below is not necesarry since :resources delivers the data
  # get '/artists' => 'artists#index'

  # root 'recording_sessions#index'
  resources :studios, :recording_sessions, :engineers, :artists, :comments

  resources :artists do # , #shallow: true do
    resources :comments # , :only => [:index, :show, :new, :edit]
  end

  resources :artists do # , #shallow: true do
    resources :recording_sessions # , :only => [:index, :show, :new, :edit]
  end

  # namespace :api do
  #   namespace :v1 do
  #     resources :artists
  #   end
  # end
end

app/models/artist.rb
class Artist < ApplicationRecord

    has_many :comments #, inverse_of: :recording_sessions
    has_many :recording_sessions #, inverse_of: :recording_sessions
    
    #adds methods to my model
    has_many :engineers, through: :recording_sessions
    has_many :studios, through: :recording_sessions
    accepts_nested_attributes_for :comments
    accepts_nested_attributes_for :recording_sessions
#    accepts_nested_attributes_for :engineers
 #   accepts_nested_attributes_for :studios

validates :name, presence: true, length: { minimum: 1 }
validates :name, uniqueness: true
#validates :email, presence: optional




  def recording_sessions_attributes=(recording_session_attributes)
    recording_session_attributes.values.each do |recording_session_attribute|
      recording_session = RecordingSession.find_or_create_by(recording_session_attribute)
      self.recording_sessions << recording_session
    end
  end
  
  
  # def engineers_attributes=(engineer_attributes)
  #   engineer_attributes.values.each do |engineer_attribute|
  #     engineer = Engineer.find_or_create_by(engineer_attribute)
  #     self.engineers << engineer
  #   end
  # end
  
  # def studios_attributes=(studio_attributes)
  #   studio_attributes.values.each do |studio_attribute|
  #     studio = Studio.find_or_create_by(studio_attribute)
  #     self.studio << studio
  #   end
  # end

end

app/controllers/artists_controller.rb
# frozen_string_literal: true

class ArtistsController < ApplicationController
  # before_filter :authenticate_user!
  # ! uncomment below
  # before_action :authenticate_user!

  # def index
  #   @artists = Artist.all
  #   @recording_sessions = RecordingSession.all
  #   @engineers = Engineer.all
  #   @studios = Studio.all
  #   #@artists = Artist.all
  # end

  def index
    artists = Artist.all
    # render json: artists
    render json:
    ArtistSerializer.new(artists).to_serialized_json
    # render json: artists
  end

  def new
    @artist = Artist.new
    #    2.times {@artist.recording_sessions.build}
  end

  def create
    # binding.pry
    @artist = Artist.new(artist_params)
    #    @artist = Artist.new(params[:name]
    # index
    # @artist = Artist.find(params[:id])
    if @artist.save
      # raise params.inspect
      #      redirect_to action: 'index' # , notice: 'Artist created'
      redirect_to @artist # , notice: 'Artist created'
    else
      # @studios = Studio.all
      # render action: 'new'
      render :new
    end
  end

  def edit
    @artist = Artist.find(params[:id])
    #   index
  end

  def update
    index
    # binding.pry
    @artist = Artist.find(params[:id])
    # raise params.inspect
    if @artist.update(params.require(:artist).permit(:name, :email))
      # binding.pry
      redirect_to artist_path(@artist)

    else
      render 'edit'
  end
  end

  # def show
  #   index
  #   # binding.pry
  #   @artist = Artist.find(params[:id])
  #     #     redirect_to action: 'index'
  #   end
  def show
    artist = Artist.find_by(id: params[:id])
    render json: artist.to_json(except: [:updated_at])
  end

  def destroy
    Artist.find(params[:id]).destroy
    redirect_to action: 'index'
    # redirect_to recording_session_path
  end

  private

  def artist_params
    params.require(:artist).permit(:name, :email, recording_session_ids: [], recording_session_attributes: %i[artist_id engineer_id studio_id appointment_date])
  end
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/views/artists/_edit_form.html.erb
<h3>
    <label>Recording Artist:</label><br>
    <h3>
        <h5>
            <%= @artist.name %>
        </h5>
        <br>
        <%=  form_for(@artist) do |p| %>
        <%= p.label :name %>
        <%= p.text_field :name %>
        <%= p.submit({:class => 'btn btn-primary'}) %>
        <% end %>
        <br>
        <br>
        <br>

        <button>
            <%= link_to "Delete", recording_session_path(@artist), 
                                     method: :delete, 
                                     data: {confirm: 'Are you sure you want to delete this session?'},
                                     :class => 'btn btn-default' %>
        </button>
        </h4>

app/views/artists/_errors.html.erb
<%if @artist.errors.any? %>
<div id="error_explanation">
    <h2>
        <%= pluralize(@artist.errors.count, "error") %>
        prohibited this item from being saved:
        <% @artist.errors.full_messages.each do |msg| %>
    </h2>
    <ul style="list-style: none;">
        <li>
            <div class="alert alert-danger"><%= msg %></div>
        </li>
        <% end %>
    </ul>
    <%  end %>

app/views/artists/edit.html.erb
<h2>Edit Session</h2>
<!-- render Errors MESSAGING -->
<%= render 'errors', form: @engineer %>


    <!-- EDIT FORM -->
<%= render 'edit_form', form: @engineer %>
   
        <!-- END OF EDIT FORM -->

app/views/artists/fnew.dateincluded.html.erb
<!-- NEW FORM -->
<%= form_for @artist, url: {action: "create"} do |p| %>

<h2>Create Artist</h2>
<%= render 'errors', from: @artist %>
<h4>
<%= form_for [@artist] do |artist_builder| %>
        <fieldset>
        <legend> Artist</legend>
<p>
            <%= artist_builder.label :name %><br />
            <%= artist_builder.text_field :name, autofocus: true, autocomplete: "name" %>
</p>
<p>
            <%= artist_builder.label :email %><br />
            <%= artist_builder.text_field :email, autofocus: true, autocomplete: "email" %>

            <%= artist_builder.submit({:class => 'btn btn-primary'}) %>



        </p>
        <% end %>
        <% end %>

        </h4>
        <!-- END OF NEW FORM -->

        <%= form_for @artist do |f| %>
        <%= f.label "Name" %>
        <%= f.text_field :name %>
        <%= f.fields_for :recording_sessions, @artist.recording_sessions.build do |recording_session_fields| %>
        <%= recording_session_fields.datetime_field :appointment_date %>
        <%= recording_session_fields.text_field :studio_id %>
        <% end %>
        <%= f.submit %>
        <% end %>

app/views/artists/fnew2.html.erb
<!-- NEW FORM -->
<%= form_for @artist, url: {action: "create"} do |f| %>

<!-- END OF NEW FORM -->

<%= f.label "Name" %>
<%= f.text_field :name %>
<br>
<br>
<%= f.fields_for :studios, @artist.studios.build do |studio_fields| %>
<%= studio_fields.text_field :name %>
<%= studio_fields.text_field :location %>
<br>
<br>
<br>
<%= f.fields_for :engineers, @artist.engineers.build do |engineer_fields| %>
<%= engineer_fields.text_field :name %>



<% end %>
<% end %>
<%= f.submit({:class => 'btn btn-primary'}) %>

<% end %>

app/views/artists/index.html.erb
<!-- USED in views/RecordingSessions/index -->

<!-- EDIT FORM -->
<!-- DISPLAY recording_session.ALL -->
<section class="main">

    <%= link_to 'logout', destroy_user_session_path, method: :delete %>


    <% if @artists.blank? %>
    <h2>There are currently no artists.</h2>
    <% else %>
    <h2>Current Artists</h2>
        <br>

        <table>
            <thead>
                <tr>
                    <th>Artist</th>
                    <th>Cancel</th>
                    <th>Artist</th>
                       <th colspan="3"></th>
                </tr>
            </thead>

            <% @artists.each do |c| %>
            <div class="well">
                <tbody>
                    <tr>
                        <td><%= link_to c.id, recording_session_path(c)%></td>
                        <td><%= link_to c.name.capitalize, artist_path(c) %></a></td>
                        <td

                            <%= link_to "Delete", c, method: :delete, data: { confirm: 'Are you sure you want to delete this recording session?' } %>
                        </td>

                    </tr>

                    <% end %>
                </tbody>
        </table>
        </div>
        <p> <% end %> </p>

        <!-- END OF EDIT FORM -->

<!-- URL LINKS -->
<!-- URL LINKS -->

<br>
<p>
    <%= link_to 'Create New Session', new_recording_session_path %> |
    <%= link_to 'Create New Studio', new_studio_path %> |
    <%= link_to 'Create New Artist', new_artist_path %> |
    <%= link_to 'Create New Engineer', new_engineer_path %>
</p>
</td>

<!-- END OF EDIT FORM -->

app/views/artists/new.html.erb
<!-- NEW FORM -->
<%= form_for @artist, url: {action: "create"} do |p| %>

<h2>Create Artist</h2>
<%= render 'errors', from: @artist %>
<h4>
<%= form_for [@artist] do |artist_builder| %>
        <fieldset>
        <legend> Artist</legend>
<p>
            <%= artist_builder.label :name %><br />
            <%= artist_builder.text_field :name, autofocus: true, autocomplete: "name" %>
</p>
<p>
            <%= artist_builder.label :email %><br />
            <%= artist_builder.text_field :email, autofocus: true, autocomplete: "email" %>

            <%= artist_builder.submit({:class => 'btn btn-primary'}) %>



        </p>
        <% end %>
        <% end %>

app/views/artists/show.html.erb
<body>

    <!-- RECORDING SESSION INFO -->
    <div>
        <h2> Artist Information </h2>
        <h3> Artist: <%= @artist.name.capitalize %> <button><%= link_to 'Edit Artist', edit_artist_path %></button> </h3>
        <br>

        <% if @artist.recording_sessions.blank? %>
        <h2>There are currently no sessions scheduled.</h2>
        <% else %>
        <h2>Scheduled Sessions</h1>
            <br>

            <table>
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Session Date</th>
                        <th>Engineer</th>
                        <th>Studio</th>
                        <th>Location</th>
                        <th>Complete</th>
                        <th>Cancel</th>
                        <th colspan="3"></th>
                    </tr>
                </thead>

                <% @artist.recording_sessions.each do |c| %>
                <tbody>
                    <tr>
                        <td><%= link_to c.id, recording_session_path(c)%></td>
                        <td><%= link_to c.appointment_date.strftime("%A %B %eth %Y at%l:%M %P"), recording_session_path(c)%></td>
                        <td><%= link_to c.engineer.name.capitalize, engineer_path(c.engineer) %></a></td>
                        <td><%= link_to c.studio.name.capitalize, studio_path(c.studio)%></td>
                        <td><%= link_to c.studio.location.capitalize, studio_path(c.studio)%></td>
                        <td><%= c.status %></td>
                        <td><a
                                href="/artists/@artist_id"><%= link_to "Delete", c, method: :delete, data: { confirm: 'Are you sure you want to delete this recording session?' } %></a>
                        </td>

                    </tr>
                    <% end %>
                </tbody>
            </table>

            <p> <% end %> </p>

    <!-- URL LINKS -->

<br>
<p>
    <%= link_to 'New Session', new_artist_recording_session_path(@artist) %> |
    <%= link_to 'Create New Studio', new_studio_path %> |
    <%= link_to 'Create New Artist', new_artist_path %> |
    <%= link_to 'Create New Engineer', new_engineer_path %>
</p>

<td><a
        href="/artists/@artist_id"><%= link_to "Delete Artist", @artist, method: :delete, data: { confirm: 'Are you sure you want to delete this this studio?' } %></a> </p>
</td>

            <!-- END OF EDIT FORM -->