config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # devise_for :users, controllers: { omniauth_callbacks: 'callbacks', registrations: 'registrations' }

  # ! use path below for testing basic setup
  # ! path below is not necesarry since :resources delivers the data
  # get '/artists' => 'artists#index'

  # root 'recording_sessions#index'
  resources :studios, :recording_sessions, :engineers, :artists, :comments

  resources :artists do # , #shallow: true do
    resources :comments # , :only => [:index, :show, :new, :edit]
  end

  resources :artists do # , #shallow: true do
    resources :recording_sessions # , :only => [:index, :show, :new, :edit]
  end

  # namespace :api do
  #   namespace :v1 do
  #     resources :artists
  #   end
  # end
end

app/models/engineer.rb
class Engineer < ApplicationRecord

    has_many :recording_sessions #adds methods to my model
    has_many :artists, through: :recording_sessions
    has_many :studios, through: :recording_sessions
    accepts_nested_attributes_for :recording_sessions
    
validates :name, presence: true, length: { minimum: 1 }
validates :name, uniqueness: true


end

app/controllers/engineers_controller.rb
class EngineersController < ApplicationController
    # before_filter :authenticate_user!
    before_action :authenticate_user!


    def index
    @engineers = Engineer.all
    @recording_sessions = RecordingSession.all
   # @engineers = Engineer.all
  #  @engineers = engineer.all
      end

def show
    #index
    # binding.pry
    @engineer = Engineer.find(params[:id])
    #     redirect_to action: 'index'
  end
def new
    @engineer = Engineer.new
  end

def create
      # binding.pry
      @engineer = Engineer.new(engineer_params)
  #    @artist = Artist.new(params[:name]
      #index
      # @artist = Artist.find(params[:id])
      if @engineer.save
        # raise params.inspect
  #      redirect_to action: 'index' # , notice: 'Artist created'
        redirect_to @engineer # , notice: 'Artist created'
      else
        # @engineers = Engineer.all
        render action: 'new'
      end
  end

  def destroy
    Engineer.find(params[:id]).destroy
    redirect_to 'index'
    #redirect_to '/engineers'
    #redirect_to recording_session_path
  end


def edit
  index
    @engineer = Engineer.find(params[:id])
 #   index
  end






def update
    #index
    #binding.pry
    @engineer = Engineer.find(params[:id])
    # raise params.inspect
    if @engineer.update(params.require(:engineer).permit(:name))
      redirect_to engineer_path(@engineer)
    else
      render 'edit'
    end
end
  private
  def engineer_params
    params.require(:engineer).permit(:name)
  end

end

app/helpers/engineers_helper.rb
module EngineersHelper
end

app/views/engineers/_edit_form.html.erb
<h3>
    <label>Recording Engineer:</label><br>
    <h3>
        <h5>
            <%= @engineer.name %>
        </h5>
        <br>
        <%=  form_for(@engineer) do |p| %>
        <%= p.label :name %>
        <%= p.text_field :name %>
        <%= p.submit({:class => 'btn btn-primary'}) %>
        <% end %>
        <br>
        <br>
        <br>

        <button>
            <%= link_to "Delete", recording_session_path(@engineer), 
                                     method: :delete, 
                                     data: {confirm: 'Are you sure you want to delete this session?'},
                                     :class => 'btn btn-default' %>
        </button>
        </h4>

app/views/engineers/_errors.html.erb
<%if @engineer.errors.any? %>
<div id="error_explanation">
    <h2>
        <%= pluralize(@engineer.errors.count, "error") %>
        prohibited this item from being saved:
        <% @engineer.errors.full_messages.each do |msg| %>
    </h2>
    <ul style="list-style: none;">
        <li>
            <div class="alert alert-danger"><%= msg %></div>
        </li>
        <% end %>
    </ul>
    <%  end %>

app/views/engineers/edit.html.erb
<h2>Edit Session</h2>
<!-- render Errors MESSAGING -->
<%= render 'errors', form: @engineer %>


    <!-- EDIT FORM -->
<%= render 'edit_form', form: @engineer %>
   
        <!-- END OF EDIT FORM -->

app/views/engineers/index.html.erb
<!-- USED in views/RecordingSessions/index -->

<!-- EDIT FORM -->
<!-- DISPLAY recording_session.ALL -->
<section class="main">

    <%= link_to 'logout', destroy_user_session_path, method: :delete %>


    <% if @engineers.blank? %>
    <h2>There are currently no engineers.</h2>
    <% else %>
    <h2>Current Engineers</h1>
        <br>

        <table>
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Engineer</th>
                    <th>Cancel</th>
                    <th colspan="3"></th>
                </tr>
            </thead>

            <% @engineers.each do |c| %>
            <div class="well">
                <tbody>
                        <tr>
                            <td><%= link_to c.id, recording_session_path(c)%></td>

                            <td><%= link_to c.name.capitalize, engineer_path(c) %></a></td>

                            <td>
                                <%= link_to "Delete", c, method: :delete, data: { confirm: 'Are you sure you want to delete this studio?' } %>
                            </td>
                        </tr>
                    <% end %>
                </tbody>
        </table>

        <p> <% end %> </p>

    <!-- URL LINKS -->

    <br>
     <p>
        <%= link_to 'Create New Session', new_recording_session_path %> |
        <%= link_to 'Create New Studio', new_studio_path %> |
        <%= link_to 'Create New Artist', new_artist_path %> |
        <%= link_to 'Create New Engineer', new_engineer_path %>
    </p>

app/views/engineers/new.html.erb
<!-- NEW FORM -->
<%= form_for @engineer, url: {action: "create"} do |p| %>

<h2>Create a New Engineer</h2>
<br>
<%= render 'errors', from: @engineer %>

<%= form_for [@engineer] do |p| %>
        <div class="field">
            <%= p.label :name %><br />
            <%= p.text_field :name, autofocus: true, autocomplete: "name" %>
        </div>

        <%= p.submit({:class => 'btn btn-primary'}) %>
        <% end %>
        <% end %>
        </h4>
        <!-- END OF NEW FORM -->

app/views/engineers/show.html.erb
<!-- USED in views/recording_sessions/index -->

<!-- EDIT FORM -->
<!-- DISPLAY Zat.ALL -->


<div>
    <h2> Engineer Information </h2>
    <h3> Engineer: <%= @engineer.name.capitalize %> <button><%= link_to 'Edit Engineer', edit_engineer_path %></button> </h3>
    <br></h3>
    <% if @engineer.recording_sessions.blank? %>
    <h2>There are currently no recording sessions scheduled.</h2>
    <% else %>
    <h2> Scheduled Recording Sessions</h2>
    <!-- <br> -->

    <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>Artist</th>
                <th>Studio</th>
                <th>Location</th>
                <th>Recording Session Date</th>
                <th>Complete</th>
                <th>Cancel</th>
                <th colspan="3"></th>
            </tr>
        </thead>

        <% @engineer.recording_sessions.each do |c| %>
        <div class="well">
            <tbody>
                <tr>
                    <td><%= link_to c.id, recording_session_path(c)%></td>
                    <td><%= link_to c.artist.name, artist_path(c.artist)%></td>
                    <td><%= link_to c.studio.name.capitalize, studio_path(c.studio)%></td>
                    <td><%= link_to c.studio.location.capitalize, studio_path(c.studio)%></td>
                    <td><%= link_to c.appointment_date.time.to_formatted_s(:rfc822), recording_session_path(c)%></td>
                    <td><%= c.status %></td>
                    <td><%= link_to "Delete", c, method: :delete, data: { confirm: 'Are you sure you want to delete this recording session?' } %>
                    </td>

                </tr>

                <% end %>
                <% end %>
                        </tbody>
                        </table>

                     <p></p>

            <!-- END OF EDIT FORM -->









            <!-- URL LINKS -->

            <br>
            <p>
                <%= link_to 'Create New Session', new_recording_session_path %> |
                <%= link_to 'Create New Studio', new_studio_path %> |
                <%= link_to 'Create New Artist', new_artist_path %> |
                <%= link_to 'Create New Engineer', new_engineer_path %>
            </p>