config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # devise_for :users, controllers: { omniauth_callbacks: 'callbacks', registrations: 'registrations' }

  # ! use path below for testing basic setup
  # ! path below is not necesarry since :resources delivers the data
  # get '/artists' => 'artists#index'

  # root 'recording_sessions#index'
  resources :studios, :recording_sessions, :engineers, :artists, :comments

  resources :artists do # , #shallow: true do
    resources :comments # , :only => [:index, :show, :new, :edit]
  end

  resources :artists do # , #shallow: true do
    resources :recording_sessions # , :only => [:index, :show, :new, :edit]
  end

  # namespace :api do
  #   namespace :v1 do
  #     resources :artists
  #   end
  # end
end

app/models/recording_session.rb
class RecordingSession < ApplicationRecord

  belongs_to :engineer
  belongs_to :artist
  belongs_to :studio
  accepts_nested_attributes_for :artist


#scope :by_status, -> status  { where(status: status) if status.present? }
#scope :recent, -> { order("recording_sessions.updated_at DESC") }

scope :incomplete, -> { where(status: false)}
#scope :recent, -> { order("recording_sessions.updated_at DESC") }
# scope :appointment_date, -> { where(appointment_date: true) }
# scope :recent, -> { order("recording_sessions.appointment_date DESC") }


validates :engineer_id, presence: true, length: { minimum: 1 }
validates :artist_id, presence: true, length: { minimum: 1 }
validates :studio_id, presence: true, length: { minimum: 1 }

#use the validation below to ensure that an appointment/session date is entered
#validates :appointment_date, presence: true, length: { minimum: 1 }
#validates :appointment_date, uniqueness: true

STATUS = {
        :incomplete => 0,
        :complete => 1
    }
    #use hash above to set up key 10:00 v3
    #clearly define meaning of #0 || #1 in context


    
    def complete?
        self.status == STATUS[:complete]    
        #self.status == 1
    end

    def incomplete?
        self.status == STATUS[:incomplete]
        #self.status == 0
    end

    def complete!
        self.status = STATUS[:complete]
        self.save
        #self.status == 0
    end

    def incomplete!
        self.status = STATUS[:incomplete]
        self.save
        #self.status == 0
    end

def self.recent
    order("recording_sessions.updated_at DESC")
  end


def artist_name=(name)
self.artist = Artist.find_by(name: name)
end

#def self.incomplete
 #   where(complete: false)
    
#end


end

app/controllers/recording_sessions_controller.rb
# frozen_string_literal: true

class RecordingSessionsController < ApplicationController
  # before_filter :authenticate_user!
  before_action :authenticate_user!
  # http_basic_authenticate_with name: "lu", password: "password", except: [:index, :show]
  # class Project < ActiveRecord::Base
  # belongs_to :artist, :class_name => 'Artist'
  # accepts_nested_attributes_for :artist, :reject_if => :all_blank
  # end

  def index
    @recording_sessions = RecordingSession.all
    # calling 'index'miltiple times because of select (@artists) method in recoriding_session_controller#new
    @engineers = Engineer.all
    @studios = Studio.all
    @artists = Artist.all

    # binding.pry
    if params[:artist_id]
      @recording_sessions = Artist.find(params[:artist_id]).recording_sessions
    #     @artist = Artist.find_by(id: params[:artist_id])
    #  if @artist.nil?
    #   redirect_to artists_path, alert: "Artist not found"
    #  else
    #   @recording_sessions = @artist.recording_sessions
    elsif params[:engineer_id]
      @recording_sessions = Engineer.find(params[:engineer_id]).recording_sessions
    elsif params[:studio_id]
      @recording_sessions = Studio.find(params[:studio_id]).recording_sessions
    end
  end

  def show
    index
    @recording_session = RecordingSession.find(params[:id])
    # binding.pry
    #     redirect_to action: 'index'
  end

  def new
    index
    # if params[:artist_id]
    # redirect_to action: 'index'

    # else
    #    @recording_session.artist.id = Artist.find(params[:artist_id])
    @recording_session = RecordingSession.new # (params[:id])
    @artist = Artist.new(params[:id])

    # end
    # @artist = Artist.find(params[:artist_id]
    # RecordingSession.artists.build
    # @recording_session.artist_name = params[:artist_created_name] unless params[:artist_created_name].empty
    # params.require(:recording_session).permit(:appointment_date, :studio_id, :engineer_id, :artist_id)
    # if artist_id or not -- that
    # if nested_--tind artist build --what is associated
  end

  def create
    #     binding.pry
    index
    # if params[:artist_id]
    # redirect_to action: 'index'
    #  @recording_session.artist_id = Artist.find(params[:artist_id])
    @recording_session = RecordingSession.new(recording_session_params)
    @artist = Artist.find(params[:recording_session][:artist_id])
    # @artist = Artist.find(params[:artist_id])
    # binding.pry

    # @recording_session = RecordingSession.find(params[:id])
    # @recording_sessions = artist.recording_sessions.create(recording_sessions_params)
    @recording_session.artist_id = @artist.id
    #  binding.pry
    # binding.pry
    if @recording_session.save
      # raise params.inspect
      # end
      #      redirect_to action: 'index' # , notice: 'Recording Session created'
      redirect_to @recording_session # , notice: 'Recording Session created'
    else
      # @studios = Studio.all
      render action: 'new'
     end
  end

  def edit
    index
    @recording_session = RecordingSession.find(params[:id])
    @recording_sessions = if params[:artist_id]
                            Artist.find(params[:artist_id]).recording_sessions
                          #     @artist = Artist.find_by(id: params[:artist_id])
                          #  if @artist.nil?
                          #   redirect_to artists_path, alert: "Artist not found"
                          #  else
                          #   @recording_sessions = @artist.recording_sessions
                          elsif params[:engineer_id]
                            Engineer.find(params[:engineer_id]).recording_sessions
                          elsif params[:studio_id]
                            Studio.find(params[:studio_id]).recording_sessions
                          else
                            RecordingSession.all
                                   #    redirect_to action: 'index'
                                 end
  end

  #   def recording_session_param
  #     params.require(:recording_session).permit(:appointment_date, :studio_id, :engineer_id, :artist_id)
  #   end

  # def update
  # @recording_session = recording_session.find(params[:id])
  # @recording_session.update(params.require(:recording_session).permit(:appointment_date, :studio, :engineer, :artist)
  # raise params.inspect
  # if @recording_session.update_attributes(recording_session_param)
  #    redirect_to action: 'show', id: @recording_session
  #  else

  #    @recording_sessions = RecordingSession.all
  #    @engineers = Engineer.all
  #    @engineer = Engineer.find(params[:id])
  #    @studios = Studio.all
  #    @artists = Artist.all
  #    render action: 'edit'
  # end
  # end

  def update
    index
    @recording_session = RecordingSession.find(params[:id])
    # raise params.inspect
    if @recording_session.update(params.require(:recording_session).permit(:appointment_date, :studio_id, :engineer_id, :artist_id, :status))
      # binding.pry
      redirect_to recording_session_path(@recording_session)

    else
      render 'edit'
  end
  end

  #   def update
  #     @recording_session = RecordingSession.find(params[:id])
  #     #@recording_session.update(params.require(:recording_session).permit(:appointment_date, :studio, :engineer, :artist)
  #     raise params.inspect
  #     if @recording_session.update_attributes(recording_session_param)
  #       redirect_to action: 'show', id: @recording_session
  #     else

  #       @recording_sessions = RecordingSession.all
  #       @engineers = Engineer.all
  #       @engineer = Engineer.find(params[:id])
  #       @studios = Studio.all
  #       @artists = Artist.all
  #       render action: 'edit'
  #     end
  #   end

  def destroy
    RecordingSession.find(params[:id]).destroy
    redirect_to action: 'index'
    # redirect_to recording_session_path
  end

  def show_studios
    @studio = Studio.find(params[:id])
  end
  # end

  def create_artist_from_name
    self.artist_name = new_artist_name unless new_artist_name.blank?
  end

  private

  def recording_session_params
    params.require(:recording_session).permit(:appointment_date, :studio_id, :engineer_id, :artist_id, :status)
  end

  # def artist_params
  #   params.require(:artist).permit(:artist_id, :name) #, :artist_created_name)
  # end
end

app/helpers/recording_sessions_helper.rb
module RecordingSessionsHelper
end

app/views/recording_sessions/_errors.html.erb
<%if @recording_session.errors.any? %>
<div id="error_explanation">
    <h2>
        <%= pluralize(@recording_session.errors.count, "error") %>
        prohibited this item from being saved:
        <% @recording_session.errors.full_messages.each do |msg| %>
    </h2>
    <ul style="list-style: none;">
        <li>
            <div class="alert alert-danger"><%= msg %></div>
        </li>
        <% end %>
    </ul>
    <%  end %>

app/views/recording_sessions/_index_form.html.erb
<h2>Scheduled Sessions</h1>
    <br>

    <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>Session Date</th>
                <th>Engineer</th>
                <th>Artist</th>
                <th>Studio</th>
                <th>Location</th>
                <th>Complete</th>
                <th>Cancel</th>
                <th colspan="3"></th>
            </tr>
        </thead>

        <% RecordingSession.incomplete.order('appointment_date ASC').each do |c| %>
        <div class="well">

                <%= c.appointment_date.strftime("%I:%M%p") %>
IS THIS WORKING???/

            <tbody>
                <tr>
                    <td><%= link_to c.id, recording_session_path(c)%></td>
                    <td><%= link_to c.appointment_date.strftime("%A %B %eth %Y at%l:%M %P"), recording_session_path(c)%>
                    </td>
                    <td><%= link_to c.engineer.name.capitalize, engineer_path(c.engineer) %></a></td>
                    <td><%= link_to c.artist.name, artist_path(c.artist)%></td>
                    <td><%= link_to c.studio.name.capitalize, studio_path(c.studio)%></td>
                    <td><%= link_to c.studio.location.capitalize, studio_path(c.studio)%></td>
                    <td><%= c.status %></td>
                    <td>
                        <%= link_to "Delete", c, method: :delete, data: { confirm: 'Are you sure you want to delete this recording session?' } %>
                    </td>
                </tr>


                <% end %>
            </tbody>
    </table>

app/views/recording_sessions/_index_nested.html.erb
<h2>

    Scheduled Sessions</h1>
    <br>

    <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>Session</th>
                <th>Duration</th>
                <th>Engineer</th>
                <th>Artist</th>
                <th>Studio</th>
                <th>Location</th>
                <th>Complete</th>
                <th>Cancel</th>
                <th colspan="3"></th>
            </tr>
        </thead>
        <% @recording_sessions.incomplete.order('appointment_date ASC').each do |c| %>
            <div class="well">
                <tbody>
                    <tr>
                        <td>
                            <%= link_to c.id, recording_session_path(c)%>
                        </td>
                        <td>
                            <%= link_to c.appointment_date.strftime("%A %B %eth %Y at%l:%M %P"), recording_session_path(c) %>
                        </td>
                        <td>
                            <%= link_to c.duration, recording_session_path(c)%>
                        </td>
                        <td>
                            <%= link_to c.engineer.name.capitalize, engineer_path(c.engineer) %>
                                </a>
                        </td>
                        <td>
                            <%= link_to c.artist.name, artist_path(c.artist)%>
                        </td>
                        <td>
                            <%= link_to c.studio.name.capitalize, studio_path(c.studio)%>
                        </td>
                        <td>
                            <%= link_to c.studio.location.capitalize, studio_path(c.studio)%>
                        </td>
                        <td>
                            <%= c.status %>
                        </td>
                        <td>
                            <%= link_to "Delete", c, method: :delete, data: { confirm: 'Are you sure you want to delete this recording session?' } %>
                        </td>
                    </tr>
                    <% end %>
                </tbody>
    </table>

app/views/recording_sessions/_nested.html.erb
<%= simple_form_for (@recording_session) do |p| %>

<h2>Create a New Session</h2>
<fieldset>
    <legend>Session</legend>

    <h5>
        <label>Session Date:</label><br>
        <%= p.datetime_field(:appointment_date, value: Time.now.strftime('%Y-%m-%dT%H:%M'), min: {:class => 'form-control'}) %>
        <br>
        <br>
        <!--  -->
        <%= render 'rec_form_sessions', from: @recording_session %>
        <%= render 'tasks_sessions', from: @recording_session %>

        <p>

</fieldset>
<fieldset>
    <!-- <legend>Artist</legend> -->
 <p>
        <input type="hidden" name="artist_id" value="<%=params[:artist_id]%>"
        <fieldset>
            <legend>Engineer</legend>

            <p>
                <%= select("recording_session", "engineer_id", @engineers.collect {|p| [ p.name, p.id] }, {prompt: 'Assign Engineer'}) %>
            </p>
        </fieldset>
    </p>

    <fieldset>
        <legend>Studios</legend>
        <p>
            <%= select("recording_session", "studio_id", @studios.collect {|p| [ p.name, p.id] }, {prompt: 'Book Studio'}) %>
        </p>

        <p>
        </p>
        </p>
    </fieldset>
</fieldset>
<br>

<%= p.submit({:class => 'btn btn-primary'}) %>
<% end %>
</h4>

<!-- END OF NEW FORM -->

app/views/recording_sessions/_new_default.html.erb
<%= simple_form_for (@recording_session) do |p| %>

<h2>Create a New Session</h2>
<fieldset>
    <legend>Session</legend>

    <h5>
        <label>Session Date:</label><br>
        <%= p.datetime_field(:appointment_date, value: Time.now.strftime('%Y-%m-%dT%H:%M'), min: {:class => 'form-control'}) %>
        <br>
        <br>
        <!--  -->
        <%= render 'rec_form_sessions', from: @recording_session %>
        <%= render 'tasks_sessions', from: @recording_session %>

        <p>

</fieldset>
<fieldset>
    <legend>Artist</legend>

    <p>
        <%= select("recording_session", "artist_id", @artists.collect {|p| [ p.name, p.id] }, {prompt: 'Select Artist'}) %>
        <br>
        <br>


        <fieldset>
            <legend>Engineer</legend>

            <p>
                <%= select("recording_session", "engineer_id", @engineers.collect {|p| [ p.name, p.id] }, {prompt: 'Assign Engineer'}) %>
            </p>
        </fieldset>
    </p>

    <fieldset>
        <legend>Studios</legend>
        <p>
            <%= select("recording_session", "studio_id", @studios.collect {|p| [ p.name, p.id] }, {prompt: 'Book Studio'}) %>
        </p>

        <p>
        </p>
        </p>
    </fieldset>
</fieldset>
<br>

<%= p.submit({:class => 'btn btn-primary'}) %>
<% end %>
</h4>

<!-- END OF NEW FORM -->

app/views/recording_sessions/edit.html.erb
<%= form_for @recording_session do |p| %>

<h2>Edit Session</h2>
<h4>Use the dropdown menus below:</h4>
<!-- Errors MESSAGING -->
<%if @recording_session.errors.any? %>
<div id="error_explanation">
    <h2>
        <%= pluralize(@recording_session.errors.count, "error") %>
        prohibited this item from being saved:
        <% @recording_session.errors.full_messages.each do |msg| %>
    </h2>
    <ul style="list-style: none;">
        <li>
            <div class="alert alert-danger"><%= msg %></div>
        </li>
        <% end %>
        <% end %>
    </ul>


    <!-- EDIT FORM -->
    <h5> 
        <label>Session Date:</label><br>
        <%= p.datetime_field(:appointment_date, {:class => 'form-control'}) %>
        <br>
        <br>
        <%= p.select :status, [['Complete', true], ['Incomplete', false]] %>

        <br>
        <br>

        <label>Studio Location:</label><br>
        <%= select("recording_session", "studio_id", @studios.collect {|p| [ p.name, p.location, p.id] }, {prompt: 'Book Studio'}) %>

        <br>
        <br>

        <label>Recording Engineer:</label><br>
        <%= select("recording_session", "engineer_id", @engineers.collect {|p| [ p.name, p.id] }, {prompt: 'Assign Engineer'}) %>

        <br>
        <br>

        <label>Recording Artist:</label><br>
        <%= select("recording_session", "artist_id", @artists.collect {|p| [ p.name, p.id] }, {prompt: 'Select Artist'} ) %>
        <br>
        <br>
        <br> 
     

        <%= p.submit({:class => 'btn btn-primary'}) %>
        <% end %>

        <br>
        <br>
        <br>
        <br>
        <button> <%= link_to "Delete", recording_session_path(@recording_session), 
                                     method: :delete, 
                                     data: {confirm: 'Are you sure you want to delete this session?'},
                                     :class => 'btn btn-default' %>
        </button>
        </h4>
        <!-- END OF EDIT FORM -->



            <p> <%= link_to 'Create New Studio', new_studio_path %> |
                <%= link_to 'Create New Session', new_recording_session_path %> |
                <%= link_to 'Create New Artist', new_artist_path %> |
                <%= link_to 'Create New Engineer', new_engineer_path %> 

app/views/recording_sessions/fedit.html.erb
<%= form_for @recording_session do |p| %>

<h2>Edit Session</h2>
<h4>Use the dropdown menus below:</h4>
<!-- Errors MESSAGING -->
<%if @recording_session.errors.any? %>
<div id="error_explanation">
    <h2>
        <%= pluralize(@recording_session.errors.count, "error") %>
        prohibited this item from being saved:
        <% @recording_session.errors.full_messages.each do |msg| %>
    </h2>
    <ul style="list-style: none;">
        <li>
            <div class="alert alert-danger"><%= msg %></div>
        </li>
        <% end %>
        <% end %>
    </ul>


    <!-- EDIT FORM -->
    <h5>
        <label>Studio Location:</label><br>
        <%= select("recording_session", "studio_id", @studios.collect {|p| [ p.name, p.location, p.id] }, {prompt: 'Book Studio'}) %>
        <br>
        <br>
        <label>Session Date:</label><br>
        <%= select("recording_session", "appointment_date", @recording_sessions.collect {|p| [ p.appointment_date, p.id] }, {prompt: 'Select Date and Time'}) %>

        <br>
        <br>
        <label>Recording Engineer:</label><br>
        <%= select("recording_session", "engineer_id", @engineers.collect {|p| [ p.name, p.id] }, {prompt: 'Assign Engineer'}) %>
        <br>
        <br>
        <label>Recording Artist:</label><br>
        <%= select("recording_session", "artist_id", @artists.collect {|p| [ p.name, p.id] }, {prompt: 'Select Artist'} ) %>
        <br>
        <br>

        <input class="w3-input w3-padding-16" type="datetime-local" placeholder="Date and time" required name="date"
            value="2019-05-21T07:00"></p>
        Session Date : <%= p.text_field(:appointment_date, {:class => 'form-control'}) %><br />
        <%= p.submit({:class => 'btn btn-primary'}) %>
        <% end %>
        <button> <%= link_to "Delete", recording_session_path(@recording_session), 
                                     method: :delete, 
                                     data: {confirm: 'Are you sure you want to delete this session?'},
                                     :class => 'btn btn-default' %>
        </button>
        </h4>
        <!-- END OF EDIT FORM -->

app/views/recording_sessions/findex.html.erb
<section class="main">
    <% if RecordingSession.all.blank? %>
    <h2>There are currently no recording sessions scheduled.</h2>

    <!-- <%elsif @recording_sessions == nil %> -->
    <!-- render /recording_sessions index form -->
    <!-- <%= render 'index_form', form: @recording_session %> -->
    <!-- <p>"NOT NESTED"</p> -->
    <% else %>
    <!-- render nested index form i.e   -->
    <%= render 'index_nested', form: @recording_session %>
<BR>

<%= link_to "LINK to ALL SESSIONS via (index_partial) ", recording_sessions_path(@recording_session), :class => 'btn btn-default' %>
<p> <% end %> </p>
       <!-- END OF INDEX FORM -->
    <!-- USED in views/RecordingSessions/index -->
    <!-- EDIT FORM -->
    <!-- DISPLAY recording_session.ALL -->

app/views/recording_sessions/fnew.html.erb
<!-- NEW FORM -->
<% render 'errors', form: @recording_session %>
<%= form_for @recording_session, url: {action: "create"} do |p| %>
<h2>Create a New Session</h2>
<h4>Use the dropdown menus below:</h4>
    <h5>
        <%= select("recording_session", "studio_id", @studios.collect {|p| [ p.name, p.id] }, {prompt: 'Book Studio'}) %>
        <br>
        <br>
        <%= select("recording_session", "appointment_date", @recording_sessions.collect {|p| [ p.appointment_date] }, {prompt: 'Select Date and Time'}) %>

        <br>
        <br>
        <%= select("recording_session", "engineer_id", @engineers.collect {|p| [ p.name, p.id] }, {prompt: 'Assign Engineer'}) %>
        <br>
        <br>
        <%= select("recording_session", "artist_id", @artists.collect {|p| [ p.name, p.id] }, {prompt: 'Select Artist'}) %>

        <br>
        <br>

        <%= p.submit({:class => 'btn btn-primary'}) %>
    
        </h4>


        <!-- END OF NEW FORM -->




<%= recording_session_builder.fields_for :artists do |artist_builder| %>
<fieldset>
    <legend> Artist</legend>
    <p>
        <%= artist_builder.label :name %><br />
        <%= artist_builder.text_field :name, autofocus: true, autocomplete: "name" %>
    </p>
    <p>
        <%= artist_builder.label :email %><br />
        <%= artist_builder.text_field :name, autofocus: true, autocomplete: "name" %>

        <%= artist_builder.submit({:class => 'btn btn-primary'}) %>
    </p>
    <% end %>
    <% end %>

app/views/recording_sessions/fnew2.html.erb
<!-- NEW FORM -->
<% render 'errors', form: @recording_session %>
<%= form_for (@recording_session) do |recording_session_builder| %>
<h2>Create a New Session</h2>
<h4>Use the dropdown menus below:</h4>
<fieldset>
    <legend>New Session</legend>

<fieldset>
    <legend>Date needs to be created</legend>

<!--  -->
    <p>
       <%= select("recording_session", "appointment_date", @recording_sessions.collect {|p| [ p.appointment_date] }, {prompt: 'Select Date and Time'}) %></>
    </p>


    <p>
        
        <%= recording_session_builder.fields_for :artists do |artist_builder| %>
    </fieldset>
    <fieldset>
        <legend>New Session</legend>
        <fieldset>
            <legend>Artist</legend>
    
            <p>
            <%= select("recording_session", "artist_id", @artists.collect {|p| [ p.name, p.id] }, {prompt: 'Select Artist'}) %>
<br>
<br>
<fieldset>
    <legend>Create New</legend>


    <%= simple_form_for(@recording_session) do |form| %> 
    <%= form.input :status %>
    <%= form.simple_fields_for(:artist) do |artist_form| %> 
    <% artist = artist_form.object.name.titleize %>
    <%= artist_form.input :name, as: :hidden %> 
    <%= artist_form.simple_fields_for(:studio) do |studio_form| %>
    <%= studio_form.input :name, label: "#{artist} Name" %> 
    <%= studio_form.input :address, label: "#{artist} Address" %>
    <% end %> 
    <% end %> 
    <%= form.submit "Submit" %> 
    <% end %>
    
    <%= artist_builder.label :name %><br />
            <%= artist_builder.text_field :name, autofocus: true, autocomplete: "name" %>
            </p>

            <p>
                <%= artist_builder.label :email %><br />
                <%= artist_builder.text_field :name, autofocus: true, autocomplete: "email" %>
            </p>
        </fieldset>
  
    </p>

 
    <p>
        <%= recording_session_builder.fields_for :engineers do |engineer_builder| %>
    
        <fieldset>
            <legend>Engineer</legend>
    
            <p>
                <%= select("recording_session", "engineer_id", @engineers.collect {|p| [ p.name, p.id] }, {prompt: 'Assign Engineer'}) %>
                <br>
                <br>
                <%= engineer_builder.label :name %><br />
                <%= engineer_builder.text_field :name, autofocus: true, autocomplete: "name" %>
            </p>
    
            <p>
                <%= engineer_builder.label :email %><br />
                <%= engineer_builder.text_field :name, autofocus: true, autocomplete: "email" %>
            </p>
        </fieldset>
    
    </p>


<%= recording_session_builder.fields_for :studios do |studio_builder| %>

<fieldset>
    <legend>Studios</legend>
        <p>
            <%= select("recording_session", "studio_id", @studios.collect {|p| [ p.name, p.id] }, {prompt: 'Book Studio'}) %>
<br>
<br>
            <%= studio_builder.label :name %><br />
            <%= studio_builder.text_field :name, autofocus: true, autocomplete: "name" %>
    </p>
    
    <p>
        <%= studio_builder.label :location %><br />
        <%= studio_builder.text_field :name, autofocus: true, autocomplete: "location" %>
    </p>
</p>
</fieldset>
</fieldset>
        <% end %>
        <% end %>
        <% end %>
        <%= recording_session_builder.submit({:class => 'btn btn-primary'}) %>
        <% end %>
        </h4>
        
        
        <!-- END OF NEW FORM -->
        
        

        

app/views/recording_sessions/index.html.erb
<section class="main">
    <% if RecordingSession.all.blank? %>
    <h2>There are currently no recording sessions scheduled.</h2>

    <!-- <%elsif @recording_sessions == nil %> -->
    <!-- render /recording_sessions index form -->
    <!-- <%= render 'index_form', form: @recording_session %> -->
    <!-- <p>"NOT NESTED"</p> -->
    <% else %>
    <!-- render nested index form i.e   -->
    <%= render 'index_nested', form: @recording_session %>
<BR>

<p> <% end %> </p>
       <!-- END OF INDEX FORM -->
    <!-- USED in views/RecordingSessions/index -->
    <!-- EDIT FORM -->
    <!-- DISPLAY recording_session.ALL -->


    <p>
        <%= link_to 'Create New Session', new_recording_session_path %> |
        <%= link_to 'Create New Studio', new_studio_path %> |
        <%= link_to 'Create New Artist', new_artist_path %> |
        <%= link_to 'Create New Engineer', new_engineer_path %>
    </p>

app/views/recording_sessions/new.html.erb
<!-- NEW FORM -->

<section class="main">

    <% if params[:artist_id] != nil %>
    <%= render 'nested', form: @recording_session %>
    <% else %>
        <%= render 'new_default', form: @recording_session %>
    <BR>

    <p> <% end %> </p>
<% render 'errors', form: (@recording_session) %>

app/views/recording_sessions/show.html.erb
<%= render 'errors', form: @recording_session %>

<!-- RECORDING SESSION INFO -->
    <div>
        <h2> Scheduled Session </h2>
<table>
    <thead>
        <tr>
            <th>ID</th>
            <th>Recording Session</th>
            <th>Engineer </th>
            <th>Studio</th>
            <th>Location</th>
            <th>Artist</th>
            <th>Complete</th>
            <th>Cancel</th>
            <th colspan="3"></th>
        </tr>
    </thead>

        <th> <%= @recording_session.id %></th>
        <th> <%= link_to @recording_session.appointment_date.strftime("%A %B %eth %Y at%l:%M %P"), recording_session_path(@recording_session) %> </th>
        <th> <%= link_to @recording_session.engineer.name, engineer_path(@recording_session.engineer_id) %> </th>
        <th> <%= link_to @recording_session.studio.name, studio_path(@recording_session.studio_id) %> </th>
        <th> <%= link_to @recording_session.studio.location, studio_path(@recording_session.studio_id) %> </th>
        <th> <%= link_to @recording_session.artist.name, artist_path(@recording_session.artist_id) %> </th>
        <th> <%= @recording_session.status%></th>

        <th><button><%= link_to "Edit", edit_recording_session_path(@recording_session), :class => 'btn btn-default' %></button></th>
        <p>
        <th><button><%= link_to "Delete", recording_session_path(@recording_session), 
                method: :delete, data: {confirm: 'Are you sure you want to delete this session?'} , :class => 'btn btn-default'%>
        </button> </th>
    </body>

    <table>

</div>
<br>
    <br>
<h5>    Create Below: </h5> 

     <%= link_to 'New Session', new_recording_session_path %> |  <%= link_to 'New Artist', new_artist_path %> |
     <%= link_to 'New Studio', new_studio_path %> |
  <%= link_to 'New Engineer', new_engineer_path %> 
</p>
    </td>