config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # devise_for :users, controllers: { omniauth_callbacks: 'callbacks', registrations: 'registrations' }

  # ! use path below for testing basic setup
  # ! path below is not necesarry since :resources delivers the data
  # get '/artists' => 'artists#index'

  # root 'recording_sessions#index'
  resources :studios, :recording_sessions, :engineers, :artists, :comments

  resources :artists do # , #shallow: true do
    resources :comments # , :only => [:index, :show, :new, :edit]
  end

  resources :artists do # , #shallow: true do
    resources :recording_sessions # , :only => [:index, :show, :new, :edit]
  end

  # namespace :api do
  #   namespace :v1 do
  #     resources :artists
  #   end
  # end
end

app/models/studio.rb
class Studio < ApplicationRecord

    has_many :recording_sessions #adds methods to my model
    has_many :engineers, through: :recording_sessions
    has_many :artists, through: :recording_sessions
    accepts_nested_attributes_for :recording_sessions

validates :name, presence: true, length: { minimum: 1 }
validates :name, uniqueness: true


end

app/controllers/studios_controller.rb
# frozen_string_literal: true

class StudiosController < ApplicationController
  # before_filter :authenticate_user!
  # before_action :authenticate_user!

  def index
    @studios = Studio.all
    @engineers = Engineer.all
    @artists = Artist.all
    @recording_sessions = RecordingSession.all
     #    redirect_to action: 'index'
   end

  def new
    @studio = Studio.new
    end

  def create
    # binding.pry
    @studio = Studio.new(studio_params)
    #    @studio = Studio.new(params[:name]
    # index
    # @studio = Artist.find(params[:id])
    if @studio.save
      # raise params.inspect
      #      redirect_to action: 'index' # , notice: 'Artist created'
      redirect_to @studio # , notice: 'Artist created'
    else
      # @studios = Studio.all
      render action: 'new'
    end
    end

  def edit
    #      binding.pry
    @studio = Studio.find(params[:id])
    #    index
    # @studios = Studio.all
    # @engineer = Engineer.find(params[:id])
    # @artist = Artist.find(params[:id])
    # @recording_session = RecordingSession.find(params[:id])
  end

  def show
    # index
    # binding.pry
    @studio = Studio.find(params[:id])
      #     redirect_to action: 'index'
    end

  def update
    # index
    # binding.pry
    @studio = Studio.find(params[:id])
    # raise params.inspect
    if @studio.update(params.require(:studio).permit(:name, :location))
      redirect_to studio_path(@studio)
    else
      render 'edit'
    end
  end

  def destroy
    Studio.find(params[:id]).destroy
    redirect_to action: 'index'
      # redirect_to recording_session_path
    end

  # end
  private

  def studio_params
    params.require(:studio).permit(:name, :location)
  end

  # end
end

app/helpers/studios_helper.rb
module StudiosHelper
end

app/views/studios/_edit_form.html.erb
<h3>
    <label>Recording Studios:</label><br>
    <h3>
        <h5>
            <%= @studio.name %>
        </h5>
        <br>
        <%=  form_for(@studio) do |p| %>
        <%= p.label :name %>
        <%= p.text_field :name %>
        <%= p.label :location %>
        <%= p.text_field :location %>
        <%= p.submit({:class => 'btn btn-primary'}) %>
        <% end %>
        <br>
        <br>
        <br>

        <button>
            <%= link_to "Delete", studio_path(@studio), 
                                     method: :delete, 
                                     data: {confirm: 'Are you sure you want to delete this session?'},
                                     :class => 'btn btn-default' %>
        </button>
        </h4>

app/views/studios/_errors.html.erb
<%if @studio.errors.any? %>
<div id="error_explanation">
    <h2>
        <%= pluralize(@studio.errors.count, "error") %>
        prohibited this item from being saved:
        <% @studio.errors.full_messages.each do |msg| %>
    </h2>
    <ul style="list-style: none;">
        <li>
            <div class="alert alert-danger"><%= msg %></div>
        </li>
        <% end %>
    </ul>
    <%  end %>

app/views/studios/edit.html.erb
<h2>Edit Session</h2>
<!-- render Errors MESSAGING -->
<%= render 'errors', form: @studio %>


    <!-- EDIT FORM -->
<%= render 'edit_form', form: @studio %>
   
<br>
<br>
<br>
                 <p> <%= link_to 'Create New Studio', new_studio_path %> |
                        <%= link_to 'Create New Session', new_recording_session_path %> 
   

        <!-- END OF EDIT FORM -->

app/views/studios/index.html.erb
<!-- USED in views/Recording_Sessions/index -->

<!-- EDIT FORM -->
<!-- DISPLAY recording_session.ALL -->
<section class="main">
<body>

    <!-- RECORDING SESSION INFO -->
    <div>
        <% if @studios.blank? %>
        <h2>There are currently no recording sessions scheduled.</h2>
        <% else %>
        <h2>Scheduled Sessions</h2>

        <table>
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Studio</th>
                    <th>Location</th>
                    <th colspan="3"></th>
                </tr>
            </thead>

            <% @studios.each do |c| %>
            <div class="well">
                <tbody>
                    <tr>
                        <td><%= link_to c.id, studio_path(c)%></td>
                        <td><%= link_to c.name.capitalize, studio_path(c) %></a></td>
                        <td><%= link_to c.location.capitalize, studio_path(c)%></td>
                        </td>
                    </tr>
                    <% end %>
                    <% end %>
                </tbody>
        </table>

                    <!-- URL LINKS -->
                    
                    <br>
                    <p>
                        <%= link_to 'Create New Session', new_recording_session_path %> |
                        <%= link_to 'Create New Studio', new_studio_path %> |
                        <%= link_to 'Create New Artist', new_artist_path %> |
                        <%= link_to 'Create New Engineer', new_engineer_path %>
                    </p>
                    </td>
                    </p>

app/views/studios/new.html.erb
<!-- NEW FORM -->
<%= form_for @studio, url: {action: "create"} do |p| %>

<h2>Create a New Studio</h2>
<br>
<%= render 'errors', from: @studio %>

<%= form_for [@studio] do |p| %>
<div class="field">
    <%= p.label :name %><br />
    <%= p.text_field :name, autofocus: true, autocomplete: "name" %> <br />
    <%= p.label :location %><br />
    <%= p.text_field :location, autofocus: true, autocomplete: "location" %> <br />
</div>

<%= p.submit({:class => 'btn btn-primary'}) %>
<% end %>
<% end %>
</h4>
<!-- END OF NEW FORM -->

app/views/studios/show.html.erb
<body>

    <!-- RECORDING SESSION INFO -->
    <div>
        <h2> Studio Information </h2>
        <h3> Studio: <%= @studio.name.capitalize %> <button><%= link_to 'Edit Studio', edit_studio_path %></button> </h3>
        <h3> Location: <%= @studio.location.capitalize %></h3>
        <br>
        <br>
        <% if @studio.recording_sessions.blank? %>
        <h2>There are currently no recording sessions scheduled.</h2>
        <% else %>
        <h2>Scheduled Sessions</h1>
            <br>

            <table>
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Session Date</th>
                        <th>Session Duration</th>
                        <th>Artist</th>
                        <th>Engineer</th>
                        <th>Complete</th>
                        <th>Cancel</th>
                        <th colspan="3"></th>
                    </tr>
                </thead>

                <% @studio.recording_sessions.each do |c| %>
                <tbody>
                    <tr>
                        <td><%= link_to c.id, recording_session_path(c)%></td>
                        <td><%= link_to c.appointment_date.strftime("%A %B %eth %Y at%l:%M %P"), recording_session_path(c)%></td>
                        <td><%= link_to c.duration, recording_session_path(c)%></td>
                        <td><%= link_to c.artist.name, artist_path(c.artist)%></td>
                        <td><%= link_to c.engineer.name.capitalize, engineer_path(c.engineer) %></a></td>
                                                <td><%= c.status %></td>
                        <td><a
                                href="/recording_sessions/@engineer_id"><%= link_to "Delete", c, method: :delete, data: { confirm: 'Are you sure you want to delete this recording session?' } %></a>
                        </td>

                    </tr>
                    <% end %>
                </tbody>
            </table>

            <p> <% end %> </p>

            <!-- END OF EDIT FORM -->

                <!-- URL LINKS -->
                
                <br>
                <p>
                    <%= link_to 'Create New Session', new_recording_session_path %> |
                    <%= link_to 'Create New Studio', new_studio_path %> |
                    <%= link_to 'Create New Artist', new_artist_path %> |
                    <%= link_to 'Create New Engineer', new_engineer_path %>
                </p>

                 <td>
                     <a href="/artists/@artist_id"><%= link_to "Delete Studio", @artist, method: :delete, data: { confirm: 'Are you sure you want to delete this this studio?' } %></a>
                 </td